### ISSUE TITLE
ML.umap appears to be an asset file and no .uasset

### ISSUE THREAD

**Issue by MannyLectro** [inworld-ai/project-origins-public#2]
Hey there!

I downloaded the project and attempted to run it with Unreal 4.27.2 but the project gives me the following error once starting:
"/DIRECTORY/ML.umap appears to be an asset file"
If I ignore the error, the project starts but appears to be empty, showing only folders. If I open the folders using the windows explorer I can see their content, but the project itself shows them as being empty.
What can I do?

Best
Manny

**Comment by MannyLectro** [comment]
Nevermind. My mistake was downloading the project directly instead of cloning it. It is working now.

**Comment by MulleDK19** [comment]
In case anyone else had this issue, you need to install Git LFS to clone this properly.
