### ISSUE TITLE
webrtc_aec_plugin.dll is missing

### ISSUE THREAD

**Issue by wangmian11** [inworld-ai/project-origins-public#3]
Copy it from the engine plugin source then it's good to go.

**Comment by CarolBaggins2023** [comment]
The plugins I obtained from the Epic market and cloned from github do not include webrtc_aec_plugin.dll. I'm sorry if I misunderstood the answer.

**Comment by CarolBaggins2023** [comment]
> The plugins I obtained from the Epic market and cloned from github do not include webrtc_aec_plugin.dll. I'm sorry if I misunderstood the answer.

I found it in the plugins of UE5.3 version. The problem has been completely solved now.
